### ISSUE TITLE
fusion dev --dir <directory> hiccups

### ISSUE THREAD

**Issue by scott-hornberger** [fusionjs/fusion-cli#562]
### Description
When running `fusion dev --dir <directory>`, I get the error:
```
Error: No entry found at /path/to/project/<directory>/<directory>/.fusion/dist/development/server/server-main.js
    at [eval]:40:20
    at ContextifyScript.Script.runInThisContext (vm.js:50:33)
    at Object.runInThisContext (vm.js:139:38)
    at Object.<anonymous> ([eval]-wrapper:6:22)
    at Module._compile (module.js:652:30)
    at evalScript (bootstrap_node.js:466:27)
    at startup (bootstrap_node.js:167:9)
    at bootstrap_node.js:612:3
```
It seems to build fine, but it can't find `server-main.js` because it's looking for `<directory>/<directory>` instead of `<directory>`. 

### Current behavior
It fails to find `/path/to/project/<directory>/<directory>/.fusion/dist/development/server/server-main.js` and will fail to find other resources because of the hiccup.

### Expected behavior
It should use  `/path/to/project/<directory>/.fusion/dist/development/server/server-main.js` and find all resources at the directory.

### Steps to reproduce

1. Scaffold a new project.
2. Move everything besides `package.json` and `node_modules` to a sub folder.  
3. Run `fusion dev --dir <subfolder>

### Your environment

* fusion-cli version: fusion, 1.11.5

* Node.js version: v8.11.4

* npm version: 5.6.0

* Operating System: Mac OS X

**Comment by scott-hornberger** [comment]
I forgot to mention: If I put a recursive symlink `<directory>` in `<directory>` that points to `<directory>` then it runs successfully!
