### ISSUE TITLE
Running fusion dev with a concurrent process causes server error that requires manual refresh

### ISSUE THREAD

**Issue by jasonbarone** [fusionjs/fusion-cli#578]
I don't know how to describe this issue. Fusion seems to struggle to recover from server errors and require a manual refresh to restart. If you run a concurrent process, such a monorepo babel watch process along with `fusion dev`, fusion will end up crashing and resulting in the following error:

```
Error: connect ECONNREFUSED 127.0.0.1:53837
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
```
You end up having to manually refresh everytime you boot up your server. 

### Type of issue
Feature request?

### Current behavior
Server errors crash Fusion in the browser and require manual refresh in browser.

### Expected behavior
Server errors should should automatically refresh the browser or recover itself if possible. 

### Steps to reproduce
I don't have a public repo for this, but can provide an Uber internal repo where this happens every time.

**Comment by KevinGrandon** [comment]
I have not seen the `Error: connect ECONNREFUSED 127.0.0.1:53837` error before.

SSR errors today do result in the "redbox error screen", which do require a full refresh to recover from. We would like to have this page automatically refreshed. We can keep this bug open to track that issue and see if it solves your manual refresh problems.
